### ISSUE TITLE
Zero: Suit Selector doesn't clear between games

### ISSUE THREAD

**Issue by stratomaster64** [Racso/fzero-apps#1]
As the title suggests, backing out of a game while the suit selector is up doesn't clear and can be brought into subsequent games as long as a suit is not selected.
Steps to reproduce:

1. Start a game of Zero and play until it's your turn and you have a wild/wild+4.
2. Select the wild/wild+4 to play. When the suit selector popup comes, press Back on the Flipper. Do not exit the app completely.
3. Press OK. A new game will start as expected, but the player will have the suit selection available even if it's not currently their turn.
Attempting to select a suit will cause the app to softock.

**Comment by Racso** [comment]
Thanks a lot for the report and the PR! Good catch!

Fixed in https://github.com/Racso/fzero-apps/commit/c30e5101322a09262f45dd4949221b2dea208d9b.
