### ISSUE TITLE
[Zero, Sokoban] Apps not building on toolchain 46.0 f7 

### ISSUE THREAD

**Issue by doomwastaken** [Racso/fzero-apps#3]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your apps to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version. 

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by Racso** [comment]
@doomwastaken Thanks for the heads up!

I'll update them when I get back home in a couple of weeks.

I guess the problem is because the API was updated with non-retrocompatible changes, right?

**Comment by doomwastaken** [comment]
Hello again, just checked your error, there is a warning from compiler, we treat them as errors. Only linter warnings are being ignored now.

**Comment by yasbean** [comment]
Compilation ends with a long list of errors beginning with:
```
	CC	/home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/save_data_manager.c
	ICONS	/home/cds/.ufbt/build/racso_sokoban/racso_sokoban_icons.c
In file included from /home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/wave/exception_manager.h:1,
                 from /home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/app.c:23:
/home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/wave/scene_management.h:4:18: error: redundant redeclaration of 'SCENE_MANAGER_NO_SCENE' [-Werror=redundant-decls]
    4 | extern const int SCENE_MANAGER_NO_SCENE;
      |                  ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/app.c:22:
/home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/wave/scene_management.h:4:18: note: previous declaration of 'SCENE_MANAGER_NO_SCENE' was here
    4 | extern const int SCENE_MANAGER_NO_SCENE;
      |                  ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/wave/exception_manager.h:1,
                 from /home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/app.c:23:
/home/cds/src/flipperzero-faps/applications_user/fzero-apps/sokoban/scripts/wave/scene_management.h:14:8: error: redundant redeclaration of 'scene_alloc' [-Werror=redundant-decls]

```

**Comment by Racso** [comment]
I've sent fixes for this issue (plus a preemptive fix for my third app). If everything goes well, I'll close this issue as soon as they're approved.

**Comment by doomwastaken** [comment]
@Racso merged https://github.com/flipperdevices/flipper-application-catalog/pull/222 thank you so much!
