### ISSUE TITLE
Update the ZERO! app for the SDK version 0.96 f7

### ISSUE THREAD

**Issue by furippa** [Racso/fzero-apps#4]
Hello!

Your ZERO app version `1.1` fails to build with the SDK version `0.96.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64e5b678c3580ee96b18cabf/page)

Flipper Team

**Comment by Racso** [comment]
I'm not sure why the bot is reporting this. That app version is an old one.
