### ISSUE TITLE
Update the Sokoban app for the SDK version 0.102 f7

### ISSUE THREAD

**Issue by furippa** [Racso/fzero-apps#6]
Hello!

Your Sokoban app version `1.2` fails to build with the SDK version `0.102.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64f1c7c2c3580ee96b18cc44/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/9163199448)

Flipper Team

**Comment by RogueMaster** [comment]
I made your needed changes on [this commit](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/891ea2ace13751b9e1cafc1f5c836f8cc61f4f01)

**Comment by Racso** [comment]
Thanks, @RogueMaster! I've opened a PR in the catalog with the fix.
